# Generated by Django 5.2.9 on 2026-03-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="year",
        ),
        migrations.RemoveField(
            model_name="subjects",
            name="year",
        ),
        migrations.AlterField(
            model_name="subjects",
            name="subject_code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
