# Generated by Django 5.2.9 on 2026-03-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("details", "0002_remove_student_year_remove_subjects_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjects",
            name="subject_code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
